services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter
      
  listings-api:
    image: node:20
    volumes:
      - ./listings-api:/app
    command: npx -y tsx ./index.ts
    working_dir: /app
    expose:
      - "3000"

  warehouse-api:
    image: node:20
    volumes:
      - ./warehouse-api:/app
    command: npx -y tsx ./index.ts
    working_dir: /app
    expose:
     - "3000"
    
  orders-api:
    image: node:20
    volumes:
      - ./orders-api:/app
    command: npx -y tsx ./index.ts
    working_dir: /app
    expose:
    - "3000"

  mongo:
    image: mongo:latest

  rabbitmq:
  image: rabbitmq:4-management
  ports:
    - "5672:5672"     
    - "15672:15672"